### ISSUE TITLE
Loading the models

### ISSUE THREAD

**Issue by cepin19** [deep-spin/robust_MT_evaluation#1]
Hi, thanks for a very interesting work and for open-sourcing the models. 
I have a clean python3.8 virtualenv and I've installed this repository and dependencies with poetry, but I'm not able to run comet-score for any of the checkpoints:

> comet-score -s ../out/news18_csen.beam20.trans -t ../news18_csen.en.snt -r ../news18_csen.en.snt --model models/comet-wl-tags/checkpoints/epoch\=1-step\=206468.ckpt 
> /home/jon/.local/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
>   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
> Global seed set to 12
> Created a temporary directory at /tmp/tmpmttoa89o
> Writing /tmp/tmpmttoa89o/_remote_module_non_scriptable.py
> Some weights of the model checkpoint at xlm-roberta-large were not used when initializing XLMRobertaModel: ['roberta.pooler.dense.weight', 'lm_head.decoder.weight', 'lm_head.dense.weight', 'lm_head.layer_norm.weight', 'roberta.pooler.dense.bias', 'lm_head.dense.bias', 'lm_head.bias', 'lm_head.layer_norm.bias']
> - This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Encoder model frozen.
> Traceback (most recent call last):
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/env2/bin/comet-score", line 6, in <module>
>     sys.exit(score_command())
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/comet/cli/score.py", line 191, in score_command
>     model = load_from_checkpoint(model_path)
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/comet/models/__init__.py", line 72, in load_from_checkpoint
>     model = model_class.load_from_checkpoint(checkpoint_path, **hparams)
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/env2/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 161, in load_from_checkpoint
>     model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/env2/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 209, in _load_model_state
>     keys = model.load_state_dict(checkpoint["state_dict"], strict=strict)
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/env2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for RegressionMetric:
> 	Missing key(s) in state_dict: "reproject_embed_layer.weight", "reproject_embed_layer.bias". 
> 	size mismatch for encoder.model.embeddings.word_embeddings.weight: copying a param with shape torch.Size([250005, 1024]) from checkpoint, the shape in current model is torch.Size([250002, 1024]).
> 	size mismatch for estimator.ff.0.weight: copying a param with shape torch.Size([3072, 8192]) from checkpoint, the shape in current model is torch.Size([3072, 6144]).
> 

> 
> comet-score -s ../out/news18_csen.beam20.trans -t ../news18_csen.en.snt -r ../news18_csen.en.snt --model models/comet-sl-feats/checkpoints/epoch\=1-step\=237518.ckpt 
> /home/jon/.local/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
>   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
> Global seed set to 12
> Created a temporary directory at /tmp/tmpucdssx8o
> Writing /tmp/tmpucdssx8o/_remote_module_non_scriptable.py
> Some weights of the model checkpoint at xlm-roberta-large were not used when initializing XLMRobertaModel: ['lm_head.layer_norm.weight', 'lm_head.decoder.weight', 'lm_head.dense.weight', 'lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.dense.bias', 'roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
> - This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Encoder model frozen.
> Traceback (most recent call last):
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/env2/bin/comet-score", line 6, in <module>
>     sys.exit(score_command())
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/comet/cli/score.py", line 191, in score_command
>     model = load_from_checkpoint(model_path)
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/comet/models/__init__.py", line 72, in load_from_checkpoint
>     model = model_class.load_from_checkpoint(checkpoint_path, **hparams)
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/env2/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 161, in load_from_checkpoint
>     model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/env2/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 209, in _load_model_state
>     keys = model.load_state_dict(checkpoint["state_dict"], strict=strict)
>   File "/lnet/work/people/jon/ga_clean/robust_MT_evaluation/env2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for RegressionMetric:
> 	Missing key(s) in state_dict: "reproject_embed_layer.weight", "reproject_embed_layer.bias". 
> 
> 

Additionally, I think the comet-aug archive is incomplete, I'm getting EOF errors when trying to extract it. What can I do to solve these problems?

**Comment by glushkovato** [comment]
Hi! Sorry for a delayed reply, there was a minor bug which is now fixed, so you shouldn't have problems using the checkpoints. The only thing you need to add yourself is the following line to the `hparams.yaml` files, depending on the model you use:

if you are running the models that don't use word-level tags, then add:
> model_type: original

otherwise:
> model_type: wl-tags

The links will be updated soon, so that others don't have to add this parameter manually, but meanwhile you can use the checkpoints with this fix. As for the comet-aug archive, I see the error, it will be reuploaded as well.

Also, in case the commands that you shared above are complete, please make sure you generate features and pass them using `-wlt` or `-f` flags if you are using wl-tags or sl-feats models accordingly.

For sentence-level features it should be a separate csv file where each column represents a feature (e.g. chrF, BLEU).
For word-level tags it should be a file with generated tags (e.g. OK / BAD) for each sentence in translation (`-t`) file.

Please, let me know if any other problems appear while using these models.

**Comment by cepin19** [comment]
Thanks a lot, I tried the sl-feats model and it works ok now! 
You are right, I didn't write the commands in full, I have the scores/features generated. Just to copy exactly your settings, how did you compute ChrF/BLEU? I'm using sacrebleu, sentence_chrf and sentence_bleu with smooth_method='exp', is that what you did? And the correct order for the model is chrf in first column, BLEU in second?

**Comment by glushkovato** [comment]
Yes, we also used sacrebleu, sentence_chrf and sentence_bleu with smooth_method='exp'.
In our case BLEU was in the first column, chrF in the second.

Btw, the links with the zipped pretrained models are updated now.
